package entitypack;

/**
 *  Class that holds all the Frames supported in uipack
 */
public enum Frame {
    MAINMENU,
    CREATEUSERACCOUNT,
    LOGIN,
    TRADINGUSERACTIONSMENU,
    ADMINACTIONSMENU,
    BROWSINGUSERACTIONSMENU,
    VIEWALLOTHERUSERSMENU,
    VIEWUSERMENU,
    TRADETOSTRING,
    VIEWPENDINGTRADESMENU,
    VIEWUSERSTATSMENU,
    VIEWITEMSANDWISHLISTMENU,
    SETACTIVESTATUSMENU,
    CREATEITEMVALIDATIONREQUESTMENU,
    SETACTIVECITYMENU,
    SENDTRADEREQUESTMENU,
    VIEWITEMVALIDATIONREQUESTS,
    SENDMESSAGEMENU,
    THRESHOLDSMENU,
    ADDNEWADMIN,
    ADMINVIEWTRADE,
    ADMINVIEWUSER,
    EDITTRADE,
    ADMINFREEZE,
    ACCEPTTRADEMENU,
    CONFIRMTRADEMENU,
    SUGGESTTRADE,
    CONFIRMREEXCHANGEMENU,
    ADDITEMTOWISHLISTMENU,
    VIEWCURRENTTHRESHOLDS,
    ITEMVIEWER,
    REMOVEFROMINVENTORY,
    ;

}
